// Generated by gencpp from file lidar_processing/feature.msg
// DO NOT EDIT!


#ifndef LIDAR_PROCESSING_MESSAGE_FEATURE_H
#define LIDAR_PROCESSING_MESSAGE_FEATURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_processing
{
template <class ContainerAllocator>
struct feature_
{
  typedef feature_<ContainerAllocator> Type;

  feature_()
    : r(0.0)
    , phi(0.0)
    , specifier(0.0)
    , knownCorr(0)  {
    }
  feature_(const ContainerAllocator& _alloc)
    : r(0.0)
    , phi(0.0)
    , specifier(0.0)
    , knownCorr(0)  {
  (void)_alloc;
    }



   typedef double _r_type;
  _r_type r;

   typedef double _phi_type;
  _phi_type phi;

   typedef double _specifier_type;
  _specifier_type specifier;

   typedef int32_t _knownCorr_type;
  _knownCorr_type knownCorr;




  typedef boost::shared_ptr< ::lidar_processing::feature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_processing::feature_<ContainerAllocator> const> ConstPtr;

}; // struct feature_

typedef ::lidar_processing::feature_<std::allocator<void> > feature;

typedef boost::shared_ptr< ::lidar_processing::feature > featurePtr;
typedef boost::shared_ptr< ::lidar_processing::feature const> featureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_processing::feature_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_processing::feature_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_processing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lidar_processing': ['/nas/ei/home/ga62saf/gruppe2/catkin_shangyin/src/lidar_processing/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg', '/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_processing::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_processing::feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_processing::feature_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_processing::feature_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_processing::feature_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_processing::feature_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_processing::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c03949e67c3c314b42ad9c8ad76ea855";
  }

  static const char* value(const ::lidar_processing::feature_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc03949e67c3c314bULL;
  static const uint64_t static_value2 = 0x42ad9c8ad76ea855ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_processing::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_processing/feature";
  }

  static const char* value(const ::lidar_processing::feature_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_processing::feature_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n\
float64 phi\n\
float64 specifier\n\
int32 knownCorr\n\
";
  }

  static const char* value(const ::lidar_processing::feature_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_processing::feature_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.phi);
      stream.next(m.specifier);
      stream.next(m.knownCorr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct feature_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_processing::feature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_processing::feature_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "specifier: ";
    Printer<double>::stream(s, indent + "  ", v.specifier);
    s << indent << "knownCorr: ";
    Printer<int32_t>::stream(s, indent + "  ", v.knownCorr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PROCESSING_MESSAGE_FEATURE_H
