// Generated by gencpp from file turtle_vis/send_desired_pose.msg
// DO NOT EDIT!


#ifndef TURTLE_VIS_MESSAGE_SEND_DESIRED_POSE_H
#define TURTLE_VIS_MESSAGE_SEND_DESIRED_POSE_H

#include <ros/service_traits.h>


#include <turtle_vis/send_desired_poseRequest.h>
#include <turtle_vis/send_desired_poseResponse.h>


namespace turtle_vis
{

struct send_desired_pose
{

typedef send_desired_poseRequest Request;
typedef send_desired_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_desired_pose
} // namespace turtle_vis


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_vis::send_desired_pose > {
  static const char* value()
  {
    return "6263a555b929382ab066ff6b05ebdd5e";
  }

  static const char* value(const ::turtle_vis::send_desired_pose&) { return value(); }
};

template<>
struct DataType< ::turtle_vis::send_desired_pose > {
  static const char* value()
  {
    return "turtle_vis/send_desired_pose";
  }

  static const char* value(const ::turtle_vis::send_desired_pose&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_vis::send_desired_poseRequest> should match 
// service_traits::MD5Sum< ::turtle_vis::send_desired_pose > 
template<>
struct MD5Sum< ::turtle_vis::send_desired_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_vis::send_desired_pose >::value();
  }
  static const char* value(const ::turtle_vis::send_desired_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_vis::send_desired_poseRequest> should match 
// service_traits::DataType< ::turtle_vis::send_desired_pose > 
template<>
struct DataType< ::turtle_vis::send_desired_poseRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_vis::send_desired_pose >::value();
  }
  static const char* value(const ::turtle_vis::send_desired_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_vis::send_desired_poseResponse> should match 
// service_traits::MD5Sum< ::turtle_vis::send_desired_pose > 
template<>
struct MD5Sum< ::turtle_vis::send_desired_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_vis::send_desired_pose >::value();
  }
  static const char* value(const ::turtle_vis::send_desired_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_vis::send_desired_poseResponse> should match 
// service_traits::DataType< ::turtle_vis::send_desired_pose > 
template<>
struct DataType< ::turtle_vis::send_desired_poseResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_vis::send_desired_pose >::value();
  }
  static const char* value(const ::turtle_vis::send_desired_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_VIS_MESSAGE_SEND_DESIRED_POSE_H
