set(_CATKIN_CURRENT_PACKAGE "move_base_tf")
set(move_base_tf_VERSION "0.0.0")
set(move_base_tf_MAINTAINER "ga62saf <ga62saf@todo.todo>")
set(move_base_tf_PACKAGE_FORMAT "2")
set(move_base_tf_BUILD_DEPENDS "roscpp" "rospy" "tf" "turtlesim" "cv_bridge" "image_transport" "sensor_msgs" "std_msgs")
set(move_base_tf_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "tf" "turtlesim" "cv_bridge" "image_transport" "sensor_msgs" "std_msgs")
set(move_base_tf_BUILDTOOL_DEPENDS "catkin")
set(move_base_tf_BUILDTOOL_EXPORT_DEPENDS )
set(move_base_tf_EXEC_DEPENDS "roscpp" "rospy" "tf" "turtlesim" "cv_bridge" "image_transport" "sensor_msgs" "std_msgs")
set(move_base_tf_RUN_DEPENDS "roscpp" "rospy" "tf" "turtlesim" "cv_bridge" "image_transport" "sensor_msgs" "std_msgs")
set(move_base_tf_TEST_DEPENDS )
set(move_base_tf_DOC_DEPENDS )
set(move_base_tf_URL_WEBSITE "")
set(move_base_tf_URL_BUGTRACKER "")
set(move_base_tf_URL_REPOSITORY "")
set(move_base_tf_DEPRECATED "")